//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coats.Crafts.SmartTartget.TestStagingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.smarttarget.tridion.com/", ConfigurationName="TestStagingService.SmartTargetDeployment")]
    public interface SmartTargetDeployment {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Coats.Crafts.SmartTartget.TestStagingService.deployResponse deploy(Coats.Crafts.SmartTartget.TestStagingService.deployRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deployRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deploy", Namespace="http://web.smarttarget.tridion.com/", Order=0)]
        public Coats.Crafts.SmartTartget.TestStagingService.deployRequestBody Body;
        
        public deployRequest() {
        }
        
        public deployRequest(Coats.Crafts.SmartTartget.TestStagingService.deployRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class deployRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public deployRequestBody() {
        }
        
        public deployRequestBody(byte[] arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deployResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deployResponse", Namespace="http://web.smarttarget.tridion.com/", Order=0)]
        public Coats.Crafts.SmartTartget.TestStagingService.deployResponseBody Body;
        
        public deployResponse() {
        }
        
        public deployResponse(Coats.Crafts.SmartTartget.TestStagingService.deployResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class deployResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public deployResponseBody() {
        }
        
        public deployResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmartTargetDeploymentChannel : Coats.Crafts.SmartTartget.TestStagingService.SmartTargetDeployment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartTargetDeploymentClient : System.ServiceModel.ClientBase<Coats.Crafts.SmartTartget.TestStagingService.SmartTargetDeployment>, Coats.Crafts.SmartTartget.TestStagingService.SmartTargetDeployment {
        
        public SmartTargetDeploymentClient() {
        }
        
        public SmartTargetDeploymentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartTargetDeploymentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartTargetDeploymentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartTargetDeploymentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Coats.Crafts.SmartTartget.TestStagingService.deployResponse Coats.Crafts.SmartTartget.TestStagingService.SmartTargetDeployment.deploy(Coats.Crafts.SmartTartget.TestStagingService.deployRequest request) {
            return base.Channel.deploy(request);
        }
        
        public bool deploy(byte[] arg0, string arg1) {
            Coats.Crafts.SmartTartget.TestStagingService.deployRequest inValue = new Coats.Crafts.SmartTartget.TestStagingService.deployRequest();
            inValue.Body = new Coats.Crafts.SmartTartget.TestStagingService.deployRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Coats.Crafts.SmartTartget.TestStagingService.deployResponse retVal = ((Coats.Crafts.SmartTartget.TestStagingService.SmartTargetDeployment)(this)).deploy(inValue);
            return retVal.Body.@return;
        }
    }
}
